    --Credits
    _G.charSelect.credit_add("Saturn Sonic Pack DX", "Mel_", "Main Head of Mod")
    _G.charSelect.credit_add("Saturn Sonic Pack DX", "OneCalledRPG", "Assembly and Support")
    _G.charSelect.credit_add("Sonic", "kurobutt", "OG Model Port and Assets")
    _G.charSelect.credit_add("Sonic", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Sonic", "Ryan Drummond", "Voicelines")
    _G.charSelect.credit_add("Tails", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Tails", "Team Ultrafix", "Tails Icon Edit")
    _G.charSelect.credit_add("Tails", "Corey Bringas", "Voicelines")
    _G.charSelect.credit_add("Tails", "Connor Bringas", "Voicelines")
    _G.charSelect.credit_add("Tails", "William Corkery", "Voicelines")
    _G.charSelect.credit_add("Knuckles", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Knuckles", "TeamUltrafix", "Knuckles Icon Edit")
    _G.charSelect.credit_add("Knuckles", "Michael McGaharn", "Voicelines")
    _G.charSelect.credit_add("Knuckles", "Ryan Drummond", "Voicelines")
    _G.charSelect.credit_add("Knuckles", "Scott Dreier", "Voicelines")
    _G.charSelect.credit_add("Amy", "SoloSlacker", "OG Model Edit and Assets")
    _G.charSelect.credit_add("Amy", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Amy", "PicsAndPixels", "Amy Icon")
    _G.charSelect.credit_add("Amy", "E-122 PSI", "Amy Icon")
    _G.charSelect.credit_add("Amy", "Jennifer Douillard", "Voicelines")
    _G.charSelect.credit_add("Mighty", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Mighty", "crappyblue", "Mighty Icon Sprite")
    _G.charSelect.credit_add("Mighty", "Yusuke Numata", "Voicelines")
    _G.charSelect.credit_add("Ray", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Ray", "WizToad", "Ray Icon Sprite")
    _G.charSelect.credit_add("Ray", "Hinako Kanamaru", "Voicelines")
    _G.charSelect.credit_add("Trip", "SoloSlacker", "OG Amy Model Edit and Assets")
    _G.charSelect.credit_add("Trip", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Trip", "miniluv73", "Trip Icon Sprite")
    _G.charSelect.credit_add("Trip", "Nicole Tompkins", "Voicelines")
    _G.charSelect.credit_add("Metal Sonic", "Mel_", "Model Edits and Coop Porting")
    _G.charSelect.credit_add("Metal Sonic", "The Lone Devil", "Metal Sonic Icon Sprite")
